services:
  db:
    image: postgres:16
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: walon
      POSTGRES_PASSWORD: walon
      POSTGRES_DB: myappdb
    ports:
      - "5100:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: walon@gmail.com
      PGADMIN_DEFAULT_PASSWORD: walon
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  pgdata:

